version: '3.8'

services:
  spring:
    container_name: spring-client
    image: spring-client
    environment:
      - TZ=Asia/Seoul
      - MYSQL_URL: ${MYSQL_URL}
      - MYSQL_USERNAME: ${MYSQL_USERNAME}
      - MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    privileged: true
    networks:
      - odd

networks:
  odd:
    external: true
