version: '3.8'

services:
  spring-client:
    container_name: spring-client
    image: spring-client
    environment:
      - TZ=Asia/Seoul
    privileged: true
    networks:
      - odd

  # spring-manager:
  #   container_name: spring-manager
  #   image: spring-manager
  #   environment:
  #     - TZ=Asia/Seoul
  #   privileged: true
  #   networks:
  #     - odd

networks:
  odd:
    external: true
