version: '3.8'

services:
  spring:
    container_name: spring-client
    image: spring-client
    environment:
      - TZ=Asia/Seoul
    privileged: true
    networks:
      - odd

networks:
  odd:
    external: true
