version: '3.8'

services:
  fastapi:
    container_name: fastapi
    image: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8000:8000"
    networks:
      - odd

networks:
  odd:
    external: true
